# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /helix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /helix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /helix/CMakeFiles /helix//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /helix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ht_no_sycl

# Build rule for target.
ht_no_sycl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ht_no_sycl
.PHONY : ht_no_sycl

# fast build rule for target.
ht_no_sycl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/build
.PHONY : ht_no_sycl/fast

#=============================================================================
# Target rules for targets named AccumulatorSectionTest

# Build rule for target.
AccumulatorSectionTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AccumulatorSectionTest
.PHONY : AccumulatorSectionTest

# fast build rule for target.
AccumulatorSectionTest/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/AccumulatorSectionTest.dir/build.make test/CMakeFiles/AccumulatorSectionTest.dir/build
.PHONY : AccumulatorSectionTest/fast

#=============================================================================
# Target rules for targets named SorterTest

# Build rule for target.
SorterTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SorterTest
.PHONY : SorterTest

# fast build rule for target.
SorterTest/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/SorterTest.dir/build.make test/CMakeFiles/SorterTest.dir/build
.PHONY : SorterTest/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/AdaptiveHoughGpuKernel.o: src/AdaptiveHoughGpuKernel.cpp.o
.PHONY : src/AdaptiveHoughGpuKernel.o

# target to build an object file
src/AdaptiveHoughGpuKernel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/AdaptiveHoughGpuKernel.cpp.o
.PHONY : src/AdaptiveHoughGpuKernel.cpp.o

src/AdaptiveHoughGpuKernel.i: src/AdaptiveHoughGpuKernel.cpp.i
.PHONY : src/AdaptiveHoughGpuKernel.i

# target to preprocess a source file
src/AdaptiveHoughGpuKernel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/AdaptiveHoughGpuKernel.cpp.i
.PHONY : src/AdaptiveHoughGpuKernel.cpp.i

src/AdaptiveHoughGpuKernel.s: src/AdaptiveHoughGpuKernel.cpp.s
.PHONY : src/AdaptiveHoughGpuKernel.s

# target to generate assembly for a file
src/AdaptiveHoughGpuKernel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/AdaptiveHoughGpuKernel.cpp.s
.PHONY : src/AdaptiveHoughGpuKernel.cpp.s

src/Application.o: src/Application.cpp.o
.PHONY : src/Application.o

# target to build an object file
src/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/Application.cpp.o
.PHONY : src/Application.cpp.o

src/Application.i: src/Application.cpp.i
.PHONY : src/Application.i

# target to preprocess a source file
src/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/Application.cpp.i
.PHONY : src/Application.cpp.i

src/Application.s: src/Application.cpp.s
.PHONY : src/Application.s

# target to generate assembly for a file
src/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/Application.cpp.s
.PHONY : src/Application.cpp.s

src/ComputingManager.o: src/ComputingManager.cpp.o
.PHONY : src/ComputingManager.o

# target to build an object file
src/ComputingManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/ComputingManager.cpp.o
.PHONY : src/ComputingManager.cpp.o

src/ComputingManager.i: src/ComputingManager.cpp.i
.PHONY : src/ComputingManager.i

# target to preprocess a source file
src/ComputingManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/ComputingManager.cpp.i
.PHONY : src/ComputingManager.cpp.i

src/ComputingManager.s: src/ComputingManager.cpp.s
.PHONY : src/ComputingManager.s

# target to generate assembly for a file
src/ComputingManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/ComputingManager.cpp.s
.PHONY : src/ComputingManager.cpp.s

src/ComputingWorker.o: src/ComputingWorker.cpp.o
.PHONY : src/ComputingWorker.o

# target to build an object file
src/ComputingWorker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/ComputingWorker.cpp.o
.PHONY : src/ComputingWorker.cpp.o

src/ComputingWorker.i: src/ComputingWorker.cpp.i
.PHONY : src/ComputingWorker.i

# target to preprocess a source file
src/ComputingWorker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/ComputingWorker.cpp.i
.PHONY : src/ComputingWorker.cpp.i

src/ComputingWorker.s: src/ComputingWorker.cpp.s
.PHONY : src/ComputingWorker.s

# target to generate assembly for a file
src/ComputingWorker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/ComputingWorker.cpp.s
.PHONY : src/ComputingWorker.cpp.s

src/Event.o: src/Event.cpp.o
.PHONY : src/Event.o

# target to build an object file
src/Event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/Event.cpp.o
.PHONY : src/Event.cpp.o

src/Event.i: src/Event.cpp.i
.PHONY : src/Event.i

# target to preprocess a source file
src/Event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/Event.cpp.i
.PHONY : src/Event.cpp.i

src/Event.s: src/Event.cpp.s
.PHONY : src/Event.s

# target to generate assembly for a file
src/Event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/Event.cpp.s
.PHONY : src/Event.cpp.s

src/EventBuffer.o: src/EventBuffer.cpp.o
.PHONY : src/EventBuffer.o

# target to build an object file
src/EventBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/EventBuffer.cpp.o
.PHONY : src/EventBuffer.cpp.o

src/EventBuffer.i: src/EventBuffer.cpp.i
.PHONY : src/EventBuffer.i

# target to preprocess a source file
src/EventBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/EventBuffer.cpp.i
.PHONY : src/EventBuffer.cpp.i

src/EventBuffer.s: src/EventBuffer.cpp.s
.PHONY : src/EventBuffer.s

# target to generate assembly for a file
src/EventBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/EventBuffer.cpp.s
.PHONY : src/EventBuffer.cpp.s

src/ZPhiPartitioning.o: src/ZPhiPartitioning.cpp.o
.PHONY : src/ZPhiPartitioning.o

# target to build an object file
src/ZPhiPartitioning.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/ZPhiPartitioning.cpp.o
.PHONY : src/ZPhiPartitioning.cpp.o

src/ZPhiPartitioning.i: src/ZPhiPartitioning.cpp.i
.PHONY : src/ZPhiPartitioning.i

# target to preprocess a source file
src/ZPhiPartitioning.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/ZPhiPartitioning.cpp.i
.PHONY : src/ZPhiPartitioning.cpp.i

src/ZPhiPartitioning.s: src/ZPhiPartitioning.cpp.s
.PHONY : src/ZPhiPartitioning.s

# target to generate assembly for a file
src/ZPhiPartitioning.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/ZPhiPartitioning.cpp.s
.PHONY : src/ZPhiPartitioning.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ht_no_sycl.dir/build.make CMakeFiles/ht_no_sycl.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... AccumulatorSectionTest"
	@echo "... SorterTest"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... ht_no_sycl"
	@echo "... src/AdaptiveHoughGpuKernel.o"
	@echo "... src/AdaptiveHoughGpuKernel.i"
	@echo "... src/AdaptiveHoughGpuKernel.s"
	@echo "... src/Application.o"
	@echo "... src/Application.i"
	@echo "... src/Application.s"
	@echo "... src/ComputingManager.o"
	@echo "... src/ComputingManager.i"
	@echo "... src/ComputingManager.s"
	@echo "... src/ComputingWorker.o"
	@echo "... src/ComputingWorker.i"
	@echo "... src/ComputingWorker.s"
	@echo "... src/Event.o"
	@echo "... src/Event.i"
	@echo "... src/Event.s"
	@echo "... src/EventBuffer.o"
	@echo "... src/EventBuffer.i"
	@echo "... src/EventBuffer.s"
	@echo "... src/ZPhiPartitioning.o"
	@echo "... src/ZPhiPartitioning.i"
	@echo "... src/ZPhiPartitioning.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

