add_subdirectory(GpuDataTransferTest)
add_subdirectory(Splitter)
add_subdirectory(SplitterUsm)
add_subdirectory(usm)
add_subdirectory(UsmWorkflowDemo)
add_subdirectory(HelixSolverUsm)
add_subdirectory(HelixSolverUsmDemo)
add_subdirectory(SplitterUsmPerformanceTest)
add_subdirectory(HelixSolverTaskPerformanceTest)
add_subdirectory(CpuHelixSolver)
add_subdirectory(CpuHelixSolverPerformanceTest)